<?php
namespace Models\Lists;

use Bitrix\Main\Entity\Query\Join;
use Bitrix\Main\Entity\ReferenceField;
use Models\AbstractIblockPropertyValuesTable;
use Models\Lists\DoctorsProcsPropertyValuesTable;


class DoctorsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 16;

    /*public static function getMap(): array
    {
        $map = [
            'PROCEDURE' => new \ReferenceField(
                'PROCEDURE',
                DoctorsProcsPropertyValuesTable::class,
                ['=this.PROCEDURE_ID' => '=ref.IBLOCK_ELEMENT_ID']
            )
        ];

        // return array_merge(parent::getMap(),$map); // TODO: Change the autogenerated stub
        return parent::getMap()+$map; // TODO: Change the autogenerated stub

    }*/
    // вариант public static function getMap() выдает почему то ошибку
    //[Error]
    //Class "ReferenceField" not found (0)
    ///home/c/cs86751/public_html/local/app/Models/Lists/DoctorsPropertyValuesTable.php:17
    //#0: Models\Lists\DoctorsPropertyValuesTable::getMap()
    //	/home/c/cs86751/public_html/bitrix/modules/main/lib/orm/entity.php:232
    //#1: Bitrix\Main\ORM\Entity->initialize(string)
    //	/home/c/cs86751/public_html/bitrix/modules/main/lib/orm/entity.php:129
    //#2: Bitrix\Main\ORM\Entity::getInstanceDirect(string)
    //	/home/c/cs86751/public_html/bitrix/modules/main/lib/orm/entity.php:108
    //#3: Bitrix\Main\ORM\Entity::getInstance(string)
    //	/home/c/cs86751/public_html/bitrix/modules/main/lib/orm/data/datamanager.php:70
    //#4: Bitrix\Main\ORM\Data\DataManager::getEntity()
    //	/home/c/cs86751/public_html/bitrix/modules/main/lib/orm/data/datamanager.php:548
    //#5: Bitrix\Main\ORM\Data\DataManager::query()
    //	/home/c/cs86751/public_html/bitrix/modules/main/lib/orm/data/datamanager.php:429
    //#6: Bitrix\Main\ORM\Data\DataManager::getList(array)
    //	/home/c/cs86751/public_html/doctors/index.php:14
    //----------
}
